### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by dradri** [LUMAIS/FIMTrack#3]
Hey there! Trying to use this again now.  And when I load the DLC output file (h5) the program is crashing with this error. 

vatsa@biolpc182:~/Desktop/vats_unifr_linux/desk/FIMTrack_210219$ ./FIMTrack_dev
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-vatsa'
importVideo> /home/vatsa/Desktop/vats_unifr_linux/desk/Q+L/e171102/b5/cropped_videos/e171102_b5_bright.mp4 imported as 'png' images to the dir: /home/vatsa/Desktop/vats_unifr_linux/desk/Q+L/e171102/b5/cropped_videos/e171102_b5_bright
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140277757594880:
  #000: ../../../src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../../src/H5Dint.c line 1205 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../../src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../../src/H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
terminate called after throwing an instance of 'H5::FileIException'
Aborted (core dumped)
vatsa@biolpc182:~/Desktop/vats_unifr_linux/desk/FIMTrack_210219$ ./FIMTrack_dev
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-vatsa'
importVideo> /home/vatsa/Desktop/vats_unifr_linux/desk/Q+L/e171004/b10/cropped_videos/e171004_b10.mp4 imported as 'png' images to the dir: /home/vatsa/Desktop/vats_unifr_linux/desk/Q+L/e171004/b10/cropped_videos/e171004_b10
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139964011527424:
  #000: ../../../src/H5D.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../../src/H5Dint.c line 1205 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #002: ../../../src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../../src/H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
    major: Symbol table
    minor: Object not found
terminate called after throwing an instance of 'H5::FileIException'
Aborted (core dumped)

help?

**Comment by luav** [comment]
Hi @dradri ,
thank you for reporting the issue.

FIMTrack is able to load properly formed HDF5 files but we indeed have issues with the DLC-produced HDF5 files, which could happen either because they use an incompatible underlying storage driver (HDF5 library relies on few storage drivers), or because of some custom extensions, or lacking metadata about the data tables, or because of some other issue.
Thus, we ended up using CSV files in Oct 2020:
https://socialfluids.slack.com/archives/C015F6MQP9U/p1602860546116300?thread_ts=1602840566.109300&cid=C015F6MQP9U

FIMTrack does not work with DLC-generated HFD5 files and we have not devoted time to solving that issue. Please use CSV format, which is the primary way to work with our FIMTrack.
